### ISSUE TITLE
Allow to configure style for importmagic

### ISSUE THREAD

**Issue by pchomik** [pilat/vscode-importmagic#4]
Hi,

Thanks for plugin but I have one request.
Could you add configuration options to set style for importmagic?
Based on documentation it is possible to configure importmagic in two ways. One is via ```set_style``` method and second via setup.cfg. I tried second way but is not working. In my opinion plugin could support any solution - both are simple.

Link to documentation: https://github.com/alecthomas/importmagic#configuration

Why such functionality will be useful. In our project we change the rule of line length. We set it to 150 chars. When I executed importmagic on my project all imports were changed to 80 chars per line. 

Thank you in advance

**Comment by pchomik** [comment]
I found that cwd is not provided for SpawnOptions. In such case probably process is executed from $HOME directory. I will try to prepare Pull Request to add project/workspace root as cwd. In such case setup.cfg file should work.

**Comment by pilat** [comment]
Hi!

I think that the second way is more difficult than first.

I can make follow solution: This extension will read user/workspace settings and pass them to the  importmagic (via set_style method).
For example this settings will called "importmagic.maxColumns", "importmagic.multiline" etc.

What about this?

**Comment by pchomik** [comment]
For me this sounds ok. I will put this configuration into workspace configuration.

**Comment by pilat** [comment]
Hi, @pchomik! At now this extension supports code styling.
