### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by petepall** [pilat/vscode-importmagic#6]
Since the latest update I see extremely slow performance on Magic Import and also high memory consumption on a small size project.

The rebuilding of the index is consuming allot of time and resources of the system.

When I disabled the magic import extension, memory consumption drops and the intelisense is working at a normal speed. Re-enable import Magic and the system slows down to the point the intelisense is not usable anymore.
I love the function from import magic to assist with the imports but with this performance level it become very difficult to use it.

Was there any change made in the way the index build is being done?

**Comment by pilat** [comment]
I think it happens because I started saving importmagic cache on disk. At now I disabled this feature and published a new release.
Can you tell me: with new release is your problem gone?

**Comment by petepall** [comment]
@pilat the performance is back to normal. Disabling the cache on disk resolved the performance issue I saw previously.

**Comment by petepall** [comment]
@pilat I was a bit too fast in closing the issue.
I have done some more coding this evening and with import magic activated I get very slow intelisense response again. If I disable the import magic extension the intelisense is working fast again but I loose the nice import functionality.

**Comment by pilat** [comment]
@petepall Do you have **files.autoSave** settings in your user or workspace settings? I could reproduce this issue with **files.autoSave="afterDelay"**. I'm going to fix this problem soon.

**Comment by petepall** [comment]
Hi Pilat, yes, I have the files.autoSave active in my settings file.

**Comment by pilat** [comment]
Hi! I realeased new verision. There is this bug was fixed.
