### ISSUE TITLE
Sorting moves future imports from the top

### ISSUE THREAD

**Issue by agalazis** [pilat/vscode-importmagic#9]
Sorting moves future imports from the top. When I do an import all imports get reordered and future imports  (from __future__ import absolute_import) are moved further in the code. This is unintended behaviour

**Comment by pilat** [comment]
Yes, you're right.
But my extension uses [importmagic](https://github.com/alecthomas/importmagic). This behaviour arises from there. I will try do something with that in the future.

**Comment by pilat** [comment]
Hi,
I think I found a solution. New release has been using iSort for add and sort imports. I hope it will be better.

**Comment by agalazis** [comment]
I can confirm it works for now. Thank you for sorting this out until Microsoft python language server get's an update which seems long from now

**Comment by agalazis** [comment]
I guess this can close then
